apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" (include "todo-skeleton.componentName" (dict "context" . "component" "api")) }}
  labels:
    {{- include "todo-skeleton.labels" (dict "context" . "component" "api") | nindent 4 }}
data:
  {{- range $k, $v := .Values.api.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
